### PR TITLE
feat: add unified favicon

### PR DESCRIPTION
**Pull request by ChristianMurphy**
Adds an icon based off

unified

converted using `convert unified.png -define icon:auto-resize=64,48,32,16 favicon.ico`

Here's how the icon looks in firefox and chrome:

Selection_029
Selection_030

### CODE REVIEW

**Comment by wooorm** [comment]
It gets pretty small; what do you think of using just the blue `u` as a favicon?

**Comment by ChristianMurphy** [comment]
Just the U could work

**Comment by Murderlon** [comment]
Cool cool. You might want to use something like https://favicon.io/ for different sizes and cross browser support.

**Comment by wooorm** [comment]
@danoszz Could you use your magic-fu to do something similar to https://github.com/get-alex/alex/issues/261 for us here as well?

In this case, the highlight colour for the `uni|fied` logo is `#0366d6` (I use a darker blue in dark mode, to have a better contrast on a dark background, but I’m guessing the favicon will be light? All colours are from [Primer](https://github.com/primer/primitives/blob/master/primitives/colors.json))
For favicons, maybe one `u` is all that can fit though.

Less important, but if you’re feeling creative, we could do with a logo to represent unified as a whole. The word marks are fine for individual projects (`re|mark`, `v|file`, etc), but unified as a collective could be represented with a new logo. A while back we came up with a couple of WIP concepts:

48796919-26698580-ed01-11e8-9c3b-3cb284ca2589
A friend of @johno made ☝️


48796993-57e25100-ed01-11e8-92ef-40b8918840c0
I thought it’d be fun to maybe do something that moves ☝️

**Comment by danoszz** [comment]
@wooorm Sure thing! I'll work on some variations and post progress in this PR.

**Comment by ChristianMurphy** [comment]
@wooorm @danoszz would it make sense to close this PR, and open a tracking ticket to discuss iconography further?

**Comment by danoszz** [comment]
@ChristianMurphy makes sense to me, I'll open a new ticket regarding the above.

**Pull request closed without merging**
