### PR TITLE
New icons

### PR DESCRIPTION
**Pull request by jletey**
With GitHub releasing [Octicons v2](https://primer.style/octicons-v2), I thought it would be appropriate to incorporate some of their 🔥 icons in the site to give it a little refresh.

Please note that there are four icons that I have not updated: [`npm`](https://github.com/johnletey/unifiedjs.github.io/blob/icons/generate/atom/icon/npm.js), [`oc`](https://github.com/johnletey/unifiedjs.github.io/blob/icons/generate/atom/icon/oc.js), [`st`](https://github.com/johnletey/unifiedjs.github.io/blob/icons/generate/atom/icon/st.js), and [`tw`](https://github.com/johnletey/unifiedjs.github.io/blob/icons/generate/atom/icon/tw.js).

Unfortunately since I don't have the correct environment variables locally, I can't test to see what these icons look like in the site - could someone with the proper setup lmk how it looks?

### CODE REVIEW

**Comment by wooorm** [comment]
Fixed the build! You should now be able to test things locally yourself!

**Comment by jletey** [comment]
Thanks @wooorm 🙏 This will make testing much easier for me and future contributors.

---

**Before:**

Shot 2020-03-05 at 10 45 38

**After:**

Shot 2020-03-05 at 10 43 29

---

I'm definitely a fan of the new icons - what does everyone else think?

**Review by wooorm — APPROVED** [review]
Looks great!

**Review by ChristianMurphy — APPROVED** [review]
LGTM, thanks @johnletey! 🙇

**Comment by jletey** [comment]
My pleasure 😄 @wooorm @ChristianMurphy

**Pull request merged**
