### PR TITLE
Add nextjs blog boilerplate in showcase

### PR DESCRIPTION
**Pull request by ixartz**
Add another project using unifiedjs in showcase page.

What is the process to generate new screenshots?

### CODE REVIEW

**Comment by wooorm** [comment]
Thanks Remi. Sorry for the long wait.

I’m going to pass on this. The showcase is a short list of a couple interesting or big projects built on unified. It’s not supposed to become a long list.
There are also probably better places for people looking for Next.js starters?

Thanks and sorry again!

**Comment by ixartz** [comment]
@wooorm, Thank for getting back to me and taking the time to respond to my pull request.

I saw you have validated: https://nextein.elmasse.io. So, I thought I could add it too.

**Comment by wooorm** [comment]
Totally understandable! There aren’t any (documented) rules.
Nextein specifically is more a wrapper than a starter, also more popular, but most importantly: it was around when this website was created 3 years ago!

It may be nice to add some point automate the screenshots and make adding things easier.
And also make it more useful: perhaps separate pages for different projects and uses? Like a tag filter or so?
But screenshots are slow (to create, and to serve) and I’m not really sure how useful having 10k repos really is 🤷‍♂️

**Comment by ixartz** [comment]
Hi @wooorm, thank you taking the time to explain it!

There are several projects who have built this kind of pages with tag filtering and screenshots (automatic or not).

Anyway, thank you for your time and evaluating my project.

**Pull request closed without merging**
