### PR TITLE
Add guide for IE

### PR DESCRIPTION
**Pull request by jasonqsong**

### CODE REVIEW

**Comment by jasonqsong** [comment]
This is discussed in https://github.com/unifiedjs/unified/issues/55 . I'm not quite sure if a "guide" is too much for this question. Perhaps a FAQ is a better place.

**Review by Murderlon — CHANGES_REQUESTED** [review]
Thanks for taking the time for making this!

As of now I'd say this guide is a bit too specific as it's just for IE. We found out browser support is a common question and, as mentioned in https://github.com/unifiedjs/unifiedjs.github.io/issues/7#issuecomment-501327740, we'd like to tackle that in a guide that encapsulates browser support in general. Moreover, the current state of the guide would need some grooming to align with the previous guides. The latter can take quite some iterations and possibly become a bit nit-picky so I have a proposal for you. If you change the following points I am willing to pick it up from there and make it comply with the previous guides.

Requested changes:

- Switch from “Use unified in Internet Explorer” to “Setting up tooling for browser support”
- Add sections for (some) of the following on how to compile unified with:
	- Rollup
	- WebPack
	- Angular CLI
	- Create React App
	- Vue CLI
- Switch from bash commands (such as `cat > src/index.js <<EOF...`) to code snippets.
- Switch from screenshots of the console to 'printing' the output as text in the guide.

Let me know if you need help or some pointers.

**Comment by wooorm** [comment]
@jasonqsong I think what @Murderlon makes a lot of sense for our use cases, but would like to express that I’m extremely grateful that you started work on this! 💪

**Comment by jasonqsong** [comment]
The proposal looks good to me :) I'm not very familiar with angular or vue. I can only help the webpack part and the react part. Besides, I think the import, async/await of ES2016+ may need to be mentioned somewhere. And TypeScript needs to turn on "esModuleInterop".

But for most React/Angular user, `npm install remark` should be enough :) I came here only because it doesn't work in the **development** build on IE.

**Comment by wooorm** [comment]
Thanks for your earlier work.

I wrote a guide in https://github.com/unifiedjs/unifiedjs.github.io/commit/c28ed5478d5787f0594eb0c414e936eab5cb0f21 and https://github.com/unifiedjs/unifiedjs.github.io/commit/61e6149e82e09e2002322d90179e2ad617535962. [See it live here](https://unifiedjs.com/learn/guide/unified-in-the-browser/).

I don’t think it’s particularly needed to talk about each and all possible tools. So I started with esbuild and esmsh.
Open to improvements!

**Pull request closed without merging**
